### ISSUE TITLE
Create new episode structure

### ISSUE THREAD

**Issue by OliverWoolland** [UoMResearchIT/docker-introduction#10]
The ordering of the course as delivered seemed wrong when delivered. 

Problems:
- Dockerhub came up too late - after lots of questions
- Docker desktop probably good as an introduction (cli focus)
- Cleaning up containers felt poorly motivated and dry
- Story would work best interleaved with material rather than separate
- Reproducibility felt awkward 
- Tags discussion was lightweight
- No ability to inspect containers, light on security and safety 

Proposed structure 

- [ ] UoMResearchIT/docker-introduction-archive#33
- [ ] UoMResearchIT/docker-introduction#8
- [x] UoMResearchIT/docker-introduction-archive#35
- [x] UoMResearchIT/docker-introduction-archive#36
- [ ] UoMResearchIT/docker-introduction#7
- [ ] UoMResearchIT/docker-introduction#6
- [ ] UoMResearchIT/docker-introduction#5
- [x] UoMResearchIT/docker-introduction-archive#40
(numbers in brackets indicate the relevant episode numbers in the current material)
